---
title: "Visual Analysis of Electric Cars Dataset"
author: "Dominik Vukelic"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, fig.show='hold', message=FALSE)
## Importing necessary libraries
library(ggplot2)
library(tidyverse)
library(scales)

Sys.setlocale("LC_TIME", "English")

```

```{r}
# Specify the relative path to your dataset within the project
dataset_path <- file.path('..', 'cleaned_starting_file', 'EV_Data_cleaned.csv')

# Importing the dataset using read.csv with na.strings parameter to indicate missing values
df <- read.csv(dataset_path, na.strings = c("", "NA"))
```

# Creating a Bar Chart of Vehicle Brands

```{r}
ggplot(df, aes(x = Brand, fill = Brand)) +
  geom_bar(colour = "black", show.legend = FALSE) +
  geom_text(stat = "count", aes(label = ..count..), vjust = -0.5) +
  labs(title = "Count of Electric Vehicle Brands",
       x = "Brand",
       y = "Count") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

# Creating a Bar Plot for Top Speeds by Vehicle Brand

```{r}
# Aggregating counts of top speeds by brand
speed_counts <- with(df, table(Brand, Top_speed_in_km_h))

barplot(speed_counts, beside = TRUE, col = rainbow(nrow(speed_counts)), main = "Distribution of Top Speeds of Electric Vehicles by Brand", xlab = "Top Speed (km/h)", ylab = "Count")
legend("topright", legend = rownames(speed_counts), fill = rainbow(nrow(speed_counts)))
```

# Creating a Scatter Plot of Acceleration vs. Top Speed

```{r}
ggplot(df, aes(x = Acceleration_to_100km_h_in_seconds, y = Top_speed_in_km_h, color = Segment)) +
  geom_point() +
  labs(title = "Acceleration vs. Top Speed of Electric Vehicles",
       x = "Acceleration (s)",
       y = "Top Speed (km/h)") +
  theme_minimal()
```

